export const PROJECT_FORM = "PROJECT_FORM";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const PROJECT_TASKS = "PROJECT_TASKS";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CURRENT_TASK = "CURRENT_TASK";
export const UPDATE_STATE = "UPDATE_STATE";
export const UPDDATE_TASK = "UPDATE_TASK";
export const RESET_CURRENTTASK = "RESET_CURRENTTASK";

export const REGISTRY_SUCCESSFUL = "REGISTRY_SUCCESSFUL";
export const REGISTRY_ERROR = "REGISTRY_ERROR";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOG_OUT = "LOG_OUT";
